### ISSUE TITLE
Listing modules causes IndexError

### ISSUE THREAD

**Issue by cudeso** [enddo/smod#2]
Ubuntu 14 with Python 2.7.6

SMOD >show
Traceback (most recent call last):
  File "smod.py", line 8, in <module>
    Interface.mainLoop()
  File "/opt/smod/System/Core/Interface.py", line 174, in mainLoop
    result 	= getattr(globals()['Command'](),input[0])(input)
  File "/opt/smod/System/Core/Interface.py", line 41, in show
    if(args[1] == 'modules'):
IndexError: list index out of range

**Comment by enddo** [comment]
Hi,
The problem was resolved. You can use tab for auto completer.
