### ISSUE TITLE
ImportError: No module named crypto.cert

### ISSUE THREAD

**Issue by Ph4k3r** [enddo/smod#8]
root@Kali:~/Downloads/smod-1.0.3/smod-1.0.3# python smod.py 
WARNING: can't import layer dns: 'DNSRRCountField' object has no attribute 'rr'
WARNING: can't import layer tls: No module named tls
WARNING: can't import layer inet6: 'SourceIP6Field' object has no attribute 'dstname'
WARNING: can't import layer snmp: name 'bind_layers' is not defined
WARNING: can't import layer x509: name 'ASN1F_optionnal' is not defined
WARNING: can't import layer dhcp6: '_DUIDField' object has no attribute 'length_from'
WARNING: can't import layer lltd: No module named lltd
WARNING: can't import layer vxlan: No module named vxlan
Traceback (most recent call last):
  File "smod.py", line 7, in <module>
    Interface.init()
  File "/root/Downloads/smod-1.0.3/smod-1.0.3/System/Core/Interface.py", line 171, in init
    plugins.load()
  File "/root/Downloads/smod-1.0.3/smod-1.0.3/System/Core/Loader.py", line 19, in load
    self.modules.update({item:imp.load_source(name, self.path + item + '.py').Module()})
  File "/root/Downloads/smod-1.0.3/smod-1.0.3/Application/modules/modbus/scanner/arpWatcher.py", line 6, in <module>
    from System.Lib.scapy.all import sniff,ARP
  File "/root/Downloads/smod-1.0.3/smod-1.0.3/System/Lib/scapy/all.py", line 46, in <module>
    from crypto import *
  File "/root/Downloads/smod-1.0.3/smod-1.0.3/System/Lib/scapy/crypto/__init__.py", line 17, in <module>
    from scapy.crypto.cert import *
ImportError: No module named crypto.cert

I'm on Kali 2, x64.
Can't get it run, thanks in advance!

**Comment by Cybereigenvector** [comment]
Did you get a solution for this problem?

**Comment by InfiniteSuns** [comment]
"pip install scapy-real" solved that for me.

**Comment by Hypnos-Kiss** [comment]
I have the same problem, and I have tried updating python-scapy, but the problem is still here puzzling me. Can you help me? thx ~

**Comment by UncleRaymondo** [comment]
@InfiniteSuns - Spot on, that did it here :)
